### ISSUE TITLE
Android Square payment

### ISSUE THREAD

**Issue by pankaj046** [square/in-app-payments-android-quickstart#14]
https://github.com/square/in-app-payments-android-quickstart/blob/master/app/src/main/java/com/example/supercookie/ConfigHelper.java

What values replace the values of "REPLACE_ME"
public static boolean serverHostSet() {
    return !CHARGE_SERVER_HOST.equals("REPLACE_ME");
  }

and
 public static boolean squareLocationIdSet() {
    return !SQUARE_LOCATION_ID_FOR_GOOGLE_PAY.equals("REPLACE_ME");
  }

please help

**Comment by havenwood** [comment]
The `CHARGE_SERVER_HOST` is the URL of the one-click deploy [Heroku backend for this example](https://developer.squareup.com/docs/in-app-payments-sdk/quick-start/step-5).

The `SQUARE_LOCATION_ID_FOR_GOOGLE_PAY` has been renamed to `GOOGLE_PAY_MERCHANT_ID` in the latest version of this repo. It is your [Merchant ID](https://support.google.com/paymentscenter/answer/7163092?hl=en) for Google Pay.
