### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mamun361054** [square/in-app-payments-android-quickstart#15]
{"errors": [{"code": "NOT_FOUND","detail": "Card nonce not found","category": "INVALID_REQUEST_ERROR"}]}

**Comment by StephenJosey** [comment]
Hi @Mamun361054! 

Is your backend using the same environment (prod or sandbox) as the one that was used to create the nonce? If not, you will receive this error.

**Comment by StephenJosey** [comment]
Hi @Mamun361054 just checking in, are you still having this issue?
