### ISSUE TITLE
Could not resolve com.squareup.sdk.in-app-payments:google-pay:1.2.0

### ISSUE THREAD

**Issue by ibop** [square/in-app-payments-android-quickstart#19]
Hey team,
Faced issue, I can't import sdk from Gradle. I get this error in logs:
`Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.2.0.
     Required by:
         project :app
      > Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.2.0.
         > Could not get resource 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/card-entry/1.2.0/card-entry-1.2.0.pom'.
            > Could not GET 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/card-entry/1.2.0/card-entry-1.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: **unable to find valid certification path to requested target**`

Seems the reason is **unable to find valid certification path to requested target**
All the other - correct. Trying to import this: implementation "com.squareup.sdk.in-app-payments:card-entry:1.2.0"
I was also trying to download .jar manually - I can't. Also was trying to download certificate from com.squareup.sdk and manually add to AndroidStudio (from settings), but also failed. 
Any suggestions?
(gradle-top also has all required fields like maven {  url 'https://sdk.squareup.com/public/android'  }

**Comment by StephenJosey** [comment]
Not sure. If I click on those links, it starts downloading the files in my browser, so it's definitely valid sources. Have you changed anything else in the `/app/build.gradle` file in the quickstart? Or is this building on your own app, not using the quickstart?

**Comment by ibop** [comment]
Thank you, @StephenJosey , for your quick answer. I tried to launch your sample-project - it doesn't work on my machine with the same problem (certificate).
BUT! I easily have done it on my WindowsOS PC 
Assume there is a problem with my Android Studio on MacOS. Closing the ticket
