### ISSUE TITLE
[QUESTION] SDK download for InAppPayments?

### ISSUE THREAD

**Issue by LeoJHarris** [square/in-app-payments-android-quickstart#24]
Hi there we are developing an android app in Xamarin that needs to interface with square API's and since there are currently no plugins in Xamarin we are developing binding libraries per iOS and android. Regarding android is there a link that we can clone the repo of the android SDK for the inAppPayments so we can build the jar/aar of the SDK?

**Comment by StephenJosey** [comment]
You can see the components of the In-App Payments SDK here: https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/ (this is a public URL, so you should have access). Please let me know if you have additional questions or concerns!

**Comment by LeoJHarris** [comment]
@StephenJosey Can are you able to get us a copy of the ICardEntryActivityComponent but marked public?

Because we don't have access to SDK source code and only the .jar and .aar files we are struggling to update the particular Interface to public. We think to resolve our issue we need to mark the interface public, and recompile the project before attempting to bind it again for our Xamarin project.

![Capture](https://user-images.githubusercontent.com/5468757/110394531-771f6b00-80d1-11eb-8d4a-96e20d68a514.PNG)

**Comment by LeoJHarris** [comment]
Hi again, just wondering we are having an issue with the interface CardEntryActivityComponent, is this class marked internal? If it is are we able to get a copy of it marked public since the binding is not finding this interface

**Comment by LeoJHarris** [comment]
Hi again sorry for the messages but our app cannot currently resolve `Lsqip/internal/SqipActivityDebounce` do you know where this is being referenced in your SDK?

**Comment by StephenJosey** [comment]
Hi @LeoJHarris that should be inside of the in-app-payments artifact. It’s used in the card-entry artifact

**Comment by LeoJHarris** [comment]
@StephenJosey found that shortly after making the post. Thanks!

**Comment by LeoJHarris** [comment]
Sorry one other question.... does the public-android/com/squareup/sdk/in-app-payments/secure-remote-commerce get referenced some where? I couldn't see it used as a dependancy in the pom files

**Comment by StephenJosey** [comment]
That's an optional artifact for BuyerVerification which is used to verify our nonces from CardEntry for the Secure Customer Authentication requirement in the UK

**Comment by LeoJHarris** [comment]
@StephenJosey appreciate the intel sorry lastly as dagger is giving me an exception currently which version of dagger is being used for 1.5.0, I assume 2.30.1 but on your public SDK url you have public-android/com/squareup/dagger2/dagger/2.19.1
