### ISSUE TITLE
Anyway to update the sqip.SQUARE_APPLICATION_ID at runtime?

### ISSUE THREAD

**Issue by LeoJHarris** [square/in-app-payments-android-quickstart#28]
While on iOS this looks possible but as this property is set in the manifest file it doesn't appear to be able to be assigned at runtime. Can you confirm if its possible to assign a value for SQUARE_APPLICATION_ID dynamically?

**Comment by StephenJosey** [comment]
The `InAppPaymentsSdk` class has a `setSquareApplicationId` method: https://developer.squareup.com/docs/api/in-app-payment/android/sqip/InAppPaymentsSdk.html#setSquareApplicationId(String).
