### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by mauta-ii-mauta** [square/in-app-payments-android-quickstart#5]
Using **Gradle 3.3.0** (classpath 'com.android.tools.build:gradle:3.3.0') and **Gradle Wrapper 4.10.1** (distributionUrl=https://services.gradle.org/distributions/gradle-4.10.1-all.zip) I get this error:
**ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.0.3.**

Is it just an issue with Gradle? How can I resolve it?

**Comment by StephenJosey** [comment]
Hi @mauta-ii-mauta! In your Android Studio, can you please try doing File > "Invalidate Caches / Restart" and see if that makes the build work?

If not, were there any other changes you made to the quickstart before receiving this error, or were you unable to get it to run after cloning the repo?

**Comment by mauta-ii-mauta** [comment]
Hello @StephenJosey . I cloned the repo again, and without changing anything i did File-> "Invalidate Caches / Restart" and got the same error. May it be something to do with the repositories settings in the **app** level **build.gradle** file?  I am using **Android Studio 3.1.1**

**Comment by StephenJosey** [comment]
Are you currently using a proxy or firewall that may be blocking the connection to Square's server? If so, could you try adding our domain or temporarily disabling it while the build happens?

**Comment by mauta-ii-mauta** [comment]
No. I'm not. Tried connecting to the sever via the web and android studio and the connection was successful. I don't understand why I'm getting this error.

**Comment by StephenJosey** [comment]
I know you said you just cloned the repo, but just to confirm, in your app gradle file can you confirm that you have the following:
```
  maven {
    url 'https://sdk.squareup.com/public/android'
  }
```

**Comment by StephenJosey** [comment]
@mauta-ii-mauta was this error ever resolved? If not, could you confirm that you're using the latest version of Android Studio?

**Comment by mauta-ii-mauta** [comment]
Yes it was sorted. I had to completely uninstall Android Studio, download it from the website and install it again
